---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-json
  - id: check-symlinks
  - id: check-yaml
  - id: detect-aws-credentials
    args:
      - --allow-missing-credentials
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: pretty-format-json
  - id: sort-simple-yaml
  - id: trailing-whitespace
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.26.3
  hooks:
  - id: yamllint
