---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: kubelet-serving-cert-approver
    app.kubernetes.io/name: kubelet-serving-cert-approver
  name: psp:kubelet-serving-cert-approver
rules:
- apiGroups:
  - policy
  resourceNames:
  - kubelet-serving-cert-approver
  resources:
  - podsecuritypolicies
  verbs:
  - use
