---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aaronkube-crossplane-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aaronclements/aaronkube-argocd.git
    targetRevision: HEAD
    path: dev/crossplane-system
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
