---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aaronkube-users
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aaronclements/aaronkube-argocd.git
    targetRevision: HEAD
    path: dev/users
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
